<div class="mb-block-mavenbird">
    <a class="helpbutton" href="https://www.mavenbird.com/" target="_blank"></a>
    <p>
        <strong><?php echo $block->getDeveloperMessage(); ?></strong>
    </p>

    <div class="mb-links">
        <div class="mb-link-item">
            <div class="icon2"></div>
            <a href="https://www.mavenbird.com/contact" target="_blank">Extension Support</a>
        </div>
        <div class="mb-link-item">
            <div class="icon3"></div>
            <a href="https://www.mavenbird.com/guide/" target="_blank">Mavenbird Guide</a>
        </div>
    </div>
</div>